name: Bug report
description: Report a problem with Katvan
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: Reproduction steps
      description: "How to trigger the problem? Please provide step by step instructions"
    validations:
      required: true

  - type: textarea
    attributes:
      label: What actually happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you expect to happen?

  - type: input
    attributes:
      label: The full version string, from the About dialog
      placeholder: "e.g. Version 0.12.0-5a957a4 (Qt 6.10.2; Typst 0.14.1) on Arch Linux (KDE; Wayland)"
