name: Feature idea
description: Suggest a new feature for Katvan
labels: ["enhancement"]

body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: "Describe the suggested feature with some detail"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why would this feature be good for Katvan?
      description: "Describe how the suggested feature would advance the project stated design goals, as detailed in the CONTRIBUTING.md file"
    validations:
      required: true
