[package]
name = "typstdriver_rs"
edition = "2021"
publish = false
rust-version = "1.80"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"

typst = "0.13.0"
typst-pdf = "0.13.0"
typst-render = "0.13.0"
typst-ide = "0.13.0"
typst-kit = { version = "0.13.0", default-features = false, features=["embed-fonts"] }

anyhow = "1"
serde_json = "1.0"
time = { version = "0.3", features=["parsing"] }

# We don't actually need IDNA support - pin a no-op adapter
idna_adapter = "=1.0.0"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = "thin"
