name: Test build the application
on:
  push:
    branches:
      - '**'
    pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730 # v4.3.1
        with:
          version: 6.8.*
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmock-dev libhunspell-dev libarchive-dev
          pip install --user mistletoe

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: 'build'
          workspaces: |
            typstdriver/rust -> ../../build/cargo/build

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build -j

      - name: Run tests
        run: ctest --output-on-failure --test-dir build

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730 # v4.3.1
        with:
          version: 6.8.*
          cache: true

      - name: Bootstrap vcpkg
        run: |
          & "$env:VCPKG_INSTALLATION_ROOT\bootstrap-vcpkg.bat" -disableMetrics

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: 'build'
          workspaces: |
            typstdriver/rust -> ../../build/x64/RelWithDebInfo/cargo/build

      - name: Configure
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"

      - name: Build
        run: cmake --build build -j --config RelWithDebInfo

      - name: Run tests
        run: ctest --output-on-failure --test-dir build

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730 # v4.3.1
        with:
          version: 6.8.*
          cache: true

      - name: Install dependencies
        run: |
          brew install googletest libarchive bartycrouch

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: 'build'
          workspaces: |
            typstdriver/rust -> ../../build/cargo/build

      # Ensures that whatever rust-toolchain installed is before the Homebrew stubs
      - name: Adjust PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0

      - name: Build
        run: cmake --build build -j

      - name: Run tests
        run: ctest --output-on-failure --test-dir build

  analyse:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Qt
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730 # v4.3.1
        with:
          version: 6.11.*
          arch: linux_gcc_64
          cache: true

      - name: Install additional dependencies
        run: |
          sudo add-apt-repository ppa:daschuer/clazy
          sudo apt-get update
          sudo apt-get install -y libgmock-dev libhunspell-dev libarchive-dev clazy

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: |
            typstdriver/rust -> ../../build/cargo/build

      - name: Run Clazy
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clazy
          cmake --build build -j

      - name: Run clippy
        run: |
          cargo clippy --no-deps --manifest-path typstdriver/rust/Cargo.toml --target-dir build/cargo/build

      - name: Install typos
        uses: taiki-e/install-action@cca35edeb1d01366c2843b68fc3ca441446d73d3 # v2.77.1
        with:
          tool: typos

      - name: Check for typos
        run: |
          typos || true
