name: Test build the application
on:
  push:
    branches:
      - '**'
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.*
          modules: 'qtpdf'
          cache: true

      - name: Install GoogleTest
        run: sudo apt install libgmock-dev

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build -j $(nproc)

      - name: Run tests
        run: ctest --output-on-failure --test-dir build
